---
- name: Transfer and execute a script.
  hosts: all
  become: true
  tasks:
     - name: Transfer the script
       copy: src=Dialog.sh dest=/home/polyrack mode=0777

     - name: Execute the script
       command: sh /home/terminal/Dialog.sh
