---

- hosts: all
  become: yes
  become_user: root
  gather_facts: no
  tasks:
  - name: update repository index
    package:
      update_cache: yes

  - name: install remmina package
    apt:
      name: remmina
