---

- hosts: all
  become: true
  gather_facts: no
  tasks:
    - name: Environment Variable
      ansible.builtin.shell: "export DISPLAY=:0"
    - name: script ausführen
      ansible.builtin.shell: "/home/terminal/Dialog.sh"
